apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::080105255913:role/codebuild-brain-app-build-service-role
      username: codebuild-admin
      groups:
        - system:masters

    - rolearn: arn:aws:iam::080105255913:role/eksctl-brain-cluster-nodegroup-bra-NodeInstanceRole-WfwoYwhR9L7N
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes