version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - docker login -u 12345anand -p Apple@123
      - echo Configuring EKS access...
      - aws sts get-caller-identity
      - aws eks update-kubeconfig --region ap-south-1 --name brain-cluster

  build:
    commands:
      - echo Building Docker image...
      - docker build -t brain-app .
      - docker tag brain-app 12345anand/brain-app:latest
      - docker push 12345anand/brain-app:latest
      - echo Deploying app...
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

  post_build:
    commands:
      - echo Deployment completed